name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install program dependencies
      run: |
        python setup.py install
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
