name: Run Saucelabs tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to run the saucelabs tests on"
        required: true
        type: choice
        options:
          - dev
          - dev2
          - qa1
          - qa2

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Env select
      run: |
        echo "Running on env: ${{ github.event.inputs.environment }}"

    - name: Sauce Connect Proxy Action
      uses: saucelabs/sauce-connect-action@v2.1.1
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
        tunnelIdentifier: "Askuity_Saucelabs_tunnel_name"
        region: "us-west"

    - name: Setup npm 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    #- run: npm install
    #- run: npm test

    - name: Checkout test suite & run test
      uses: actions/checkout@v2

    - run: ls
    - run: npm -v
    - run: node app.js &

    - run: curl http://localhost:3000

    - run: sleep 180
