name: Run Saucelabs tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to run the saucelabs tests on"
        required: true
        type: choice
        options:
          - dev
          - dev2
          - qa1
          - qa2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Env select
      run: |
        echo "Running on env: ${{ github.event.inputs.environment }}"

    - name: Setup npm 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout test suite & run test
      uses: actions/checkout@v2

    - run: ls
    - run: npm -v
    - run: node app.js &

    - run: curl http://localhost:3000

    - name: Copy secret to file
      run: |
        cat ${{ secrets.CREDENTIALS }} > credentials.yaml

    - run: sleep 180
